name: docs
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:


  deploy:
    runs-on: ubuntu-latest

    steps:
      uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EXTRA_PACKAGES: markdown-captions mkdocstrings[python] mkdocs-nav-weight
